controller_manager:
  ros__parameters:
    update_rate: 10 # Hz

    # Controller for executing joint-space trajectories on a group of joints. 
    # The controller interpolates in time between the points so that their distance can be arbitrary. 
    # Even trajectories with only one point are accepted.  Trajectories are specified as a set of 
    # waypoints to be reached at specific time instants, which the controller attempts to execute 
    # as well as the mechanism allows. Waypoints consist of positions, and optionally velocities and accelerations.
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # reads all state interfaces and reports them on /joint_states, which robot_state_publisher subscribes to
    # and uses to update its frames
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"

    command_interfaces: # command interfaces specify what commands this controller sends down
      - position

    state_interfaces: # state interfaces specify what feedback data the controller expects
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectories: true

gripper_controller:
  ros__parameters:
    joints:
      - "6"
    interface_name: position

    command_interfaces:
      - position

    state_interfaces:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectories: true
